---
# NFS volume that is being shared among all ray node.
# see https://docs.staroid.com/ske/storage.html for more details.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  annotations:
    storage.staroid.com/scope: Instance
    storage.staroid.com/file-manager: "1000:100" # ray uid/gid
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
