# derived from https://github.com/ray-project/ray/blob/master/doc/kubernetes/ray-cluster.yaml

# Ray dashboard service.
apiVersion: v1
kind: Service
metadata:
  name: ray-dashboard
  annotations:
    service.staroid.com/link: "show"
spec:
  ports:
    - name: ray-dashboard
      port: 8265
  selector:
    component: ray-head
